name: ChemicalWarfare
author: Kolterdyx
version: '${project.version}'
main: me.kolterdyx.chemicalwarfare.ChemicalWarfare
api-version: 1.18
commands:
  gas:
    description: Create gas canisters, masks, clouds, or clear all the existing gas clouds
    usage: /gas <mustard [tier] | chlorine [tier] | tear [tier] | canister <tier> [gas] | mask <tier> [gas] | clear>
    permission: chemicalwarfare.admin
  cwpack:
    description: Download the resource pack
    usage: /cwpack
